### ISSUE TITLE
Request to update cloudpickle to 1.2.2

### ISSUE THREAD

**Issue by ksangeek** [AnacondaRecipes/cloudpickle-feedstock#1]
A recent fix https://github.com/cloudpipe/cloudpickle/pull/299 in `cloudpickle` (which also affects Dask DataFrame ) for python 3.6 has been picked up in the latest release `1.2.2` of `cloudpickle`. That release has already made into `conda-forge` channel - https://anaconda.org/conda-forge/cloudpickle.

I just wanted to gently check if the new version can be picked up in anaconda's `defaults` channel. Thank you!

**Comment by jjhelmus** [comment]
cloudpickle 1.2.2 is now available in `defaults`

**Comment by ksangeek** [comment]
Hi @jjhelmus Thanks for the quick help with updating the recipe.
Could you pls kindly check on why that change is not yet reflecting in the channel - https://anaconda.org/anaconda/cloudpickle. It still shows `1.2.1` with `Last upload: 2 months and 10 days ago`.

**Comment by ksangeek** [comment]
Nevermind, I see it has been updated now. Thank you!
